routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Middleware\Localization;

Route::get('/', function () {
    return redirect('/'. App::getLocale());
});
Route::get('lang/{locale}', 'HomeController@lang')->name('lang');

Route::get('/home', function (){
    return redirect('/'. App::getLocale());
})->name('home');

Route::group(['prefix' => Localization::getLocale()], function(){
    Auth::routes();
    Route::group(['prefix' => 'account'], function(){
        Route::middleware('can:accessAccount')->group(function(){
            /**
             * Admin part of routes
             */

            Route::resource('users', 'Admin\UsersController');
            Route::resource('restaurant-types', 'Admin\RestaurantTypes');
            Route::resource('cities', 'Admin\Cities');
            Route::resource('kitchens', 'Admin\KitchensController');
            Route::resource('restaurants', 'Admin\RestaurantsController');
            Route::resource('articles', 'Admin\ArticlesController');
            Route::resource('questions', 'Admin\QuestionController');
            Route::resource('roles', 'Admin\RolesController');
            Route::resource('event_types', 'Admin\EventTypeController');
            Route::resource('events', 'Admin\EventController');
            Route::resource('landings', 'Admin\LandingController');

            Route::resource('halls', 'Admin\HallsController')->only([
                'edit', 'update', 'destroy'
            ]);
            Route::get('/restaurants/{id}/halls/create', 'Admin\HallsController@create')->name('halls.create');
            Route::post('/restaurants/{id}/halls/store', 'Admin\HallsController@store')->name('halls.store');

            Route::resource('gallery', 'Admin\GalleryController')->only([
                'edit', 'update'
            ]);
            Route::resource('menu', 'Admin\MenuController')->only([
                'edit', 'update'
            ]);

            Route::resource('event_gallery', 'Admin\EventGalleryController')->only([
                'edit', 'update', 'destroy'
            ]);
            Route::get('/events/{id}/event_gallery/create', 'Admin\EventGalleryController@create')->name('event_gallery.create');
            Route::post('/events/{id}/event_gallery/store', 'Admin\EventGalleryController@store')->name('event_gallery.store');
            Route::post('/events/{id}/event_gallery/ajax_upload', 'Admin\AjaxUploadController@ajaxEventUpload')->name('event_gallery.ajax_upload');

            Route::post('/restaurants/{id}/halls/upload', 'Admin\AjaxUploadController@ajaxHallUpload')->name('halls.ajax_upload');
            Route::post('/restaurants/{id}/gallery/upload', 'Admin\AjaxUploadController@ajaxRestaurantUploadImage')->name('gallery.ajax_upload');
            Route::post('/restaurants/{id}/menu/upload', 'Admin\AjaxUploadController@ajaxMenuUploadImage')->name('menu.ajax_upload');
            Route::get('/remove-gallery-item/{id}', 'Admin\AjaxUploadController@removeGalleryItem')->name('remove_gallery_item'); //now must be get, because i don`t want write js of find solution for implementing delete method

            Route::get('/workload', 'Admin\WorkloadController@index')->name('workload-list');
            Route::get('/workload/{id}', 'Admin\WorkloadController@placeWorkload')->name('workload-place');
            Route::post('/workload/change-status', 'Admin\WorkloadController@changeStatus')->name('change-schedule');

            //Staff routes
            Route::get('/restaurants/{id}/staff/create', 'Admin\RestaurantsController@createStaff')->name('staff.create');
            Route::post('/restaurants/staff/store', 'Admin\RestaurantsController@storeStaff')->name('staff.store');
            Route::delete('/restaurant/staff/{id}/destroy', 'Admin\RestaurantsController@destroyStaff')->name('staff.destroy');

            Route::middleware('can:editSettings')->group(function(){
                Route::get('/resizes', 'Admin\ImageController@index')->name('resize-buttons');
                Route::post('/clean_resizes', 'Admin\ImageController@removeResizes')->name('clean-resizes');
                Route::post('/resize_one', 'Admin\ImageController@resizeOne')->name('resize-one');
                Route::post('/remove-wrong', 'Admin\ImageController@removeWrong')->name('remove-wrong');
            });
            /**
             * User part of cabinet routes
             */
            Route::get('/verified_notice', 'Account\SMSVerification@verifiedNotice')->name('phone_verification_notice');
            Route::post('/verified_notice', 'Account\SMSverification@checkVerification')->name('check_verification');
            Route::get('/send_verification_code', 'Account\SMSVerification@sendVerificationCode')->name('send_verification');
            Route::get('/dashboard', 'Account\Dashboard@index')->name('account')->middleware('phone_verified');

            Route::resource('my-orders', 'Account\OrderController');
            Route::resource('pouch', 'Account\PouchController');
            Route::resource('transactions', 'Account\TransactionsController');
            Route::resource('account-settings', 'Account\UserController');
            /**
             * Routes for restaurant management
             */
            Route::get('/restaurant/{restaurant_id}/orders', 'RestaurantManagement\OrdersController@index')->name('restaurant.orders');
            Route::get('/restaurant/{restaurant_id}/orders/{order_id}', 'RestaurantManagement\OrdersController@show')->name('restaurant.orders.show');
            Route::get('/restaurant/{restaurant_id}/orders/{order_id}/edit', 'RestaurantManagement\OrdersController@edit')->name('restaurant.orders.edit');
            Route::put('/restaurant/orders/{order_id}/update', 'RestaurantManagement\OrdersController@update')->name('restaurant.orders.update');
            Route::put('/restaurant/orders/{order_id}/accept', 'RestaurantManagement\OrdersController@accept')->name('restaurant.orders.accept');
            Route::put('/restaurant/orders/{order_id}/reject', 'RestaurantManagement\OrdersController@reject')->name('restaurant.orders.reject');
            Route::put('/restaurant/orders/{order_id}/user_reject', 'RestaurantManagement\OrdersController@user_cancel')->name('restaurant.orders.user_reject');
            //pay
            //check for payed and cancel if not
            //user reject with back money
            //success
            //confirm success


        });
    });

    Route::get('/create-sitemap', 'SitemapController@index')->name('sitemap');
    //Route::get('/test', 'LiqpayController@create');
    Route::get('/', 'HomeController@index')->name('start');
    Route::post('/show_city', 'HomeController@cities_form')->name('select-city');
    Route::get('/FAQ', 'ArticlesController@view_faq')->name('faq');
    Route::get('/{uri}', 'HomeController@city')->name('city-page');
    Route::get('/articles/{article_uri}', 'ArticlesController@index')->name('view-article');
    Route::get('/{city_ur}/filter', 'HomeController@filter')->name('filter');
    Route::get('/{city_uri}/{restaurant_uri}', 'RestaurantController@index')->name('restaurant-page');
    Route::post('/{city_uri}/{restaurant_uri}/order', 'OrdersController@create')->name('order.create');
    Route::get('/{city_uri}/{restaurant_uri}/order', 'OrdersController@continue')->name('order.continue');
    Route::post('/{restaurant}/order/store', 'OrdersController@store')->name('order.store');

});

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $fillable = ['name'];

    public $timestamps = false;

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function languages()
    {
        return $this->morphMany(Language::class, 'owner');
    }
}

app/Http/Controllers/Admin/RolesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\RestaurantTypesLangs as TypesLangs;
use App\Role;
use App\Language;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;

class RolesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['roles'] = Role::with('languages')->get();
        return view('admin.roles.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.roles.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
           'alias'            => 'string|required|unique:roles',
           'langs.*.name'     => 'string|required',
        ]);

        $role = new Role();

        $role->alias             = $request->alias;
        $role->restaurant_role   = isset($request->restaurant_role) && $request->restaurant_role === "on";
        $role->save();

        $langs = [];
        foreach($request->langs as $key => $lang) {
            $langs[$key] = new Language();
            $langs[$key]->fill(array(
                'language'              => $key,
                'name'              => $lang['name'],
            ));
            $role->languages()->save($langs[$key]);
        }

        return redirect()->route('roles.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['item'] = Role::with('languages')->findOrFail($id);
        return view('admin.roles.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'alias'            => [
                'string',
                'required',
                Rule::unique('roles')->ignore($id),
                ],
            'langs.*.name'     => 'string|required',
        ]);

        $role = Role::with('languages')->findOrFail($id);

        $role->alias = $request->alias;
        $role->restaurant_role   = isset($request->restaurant_role) && $request->restaurant_role === "on";
        $role->save();

        $langs = [];
        foreach ($request->langs as $key => $lang) {
            foreach ($role->languages as $role_lang) {
                if ($role_lang->language == $key) {
                    $role_lang->name = $lang['name'];
              }
                $role_lang->save();
            }
        }

        
        return redirect()->route('roles.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = Role::findOrFail($id);
        $role->languages()->delete();
        $role->delete();

        return redirect()->route('roles.index');
    }
}

resources/views/admin/roles/form.blade.php
@extends('layouts.account')
@section('seo')
    <title>@lang('management.roles.form.page_title')</title>
@endsection
@section('main')
    <div class="row">
        <div class="col s12">
            <h1 class="flow-text">
                @if(isset($item))
                    @foreach($item->languages as $lang)
                        @if($lang->language == app()->getLocale())
                            {{ $lang->name }}
                        @endif
                    @endforeach
                @else
                    @lang('management.roles.form.title')

                @endif
            </h1>
            <div class="card">
                <div class="card-content">
                    <div class="row">
                        @if(isset($item))
                            <form class="col s12" method="post"
                                  action="{{ route('roles.update', ['id' => $item->id]) }}">
                                @method('PATCH')
                                @else
                                    <form class="col s12" method="post" action="{{ route('roles.store') }}">
                                        @endif
                                        @csrf
                                        <div class="row">
                                            <div class="col s12 right-align">
                                                <button class="btn waves-effect waves-light" type="submit">
                                                    @lang('management.roles.form.save')

                                                    <i class="material-icons right">save</i>
                                                </button>
                                            </div>
                                        </div>
                                        @if ($errors->count() > 0)
                                            <div class="row">
                                                <ul class="col s-12">
                                                    @foreach ($errors->all() as $error)
                                                        <li>{{ $error }}</li>
                                                    @endforeach
                                                </ul>
                                            </div>
                                        @endif

                                        <div class="row">
                                            @foreach(config('app.locales') as $lang)
                                                @if(isset($item))
                                                    @if($item->languages->count() > 0)
                                                        @foreach($item->languages as $i_lang)
                                                            @if($lang == $i_lang->language)
                                                                <div class="input-field col s12">
                                                                    <input type="text" id="name_{{$lang}}"
                                                                           name="langs[{{$lang}}][name]"
                                                                           value="{{$i_lang->name}}" required/>
                                                                    <label for="name_{{$lang}}"
                                                                           class="active">@lang('management.roles.form.name')
                                                                        ({{$lang}})</label>
                                                                </div>
                                                            @endif
                                                        @endforeach
                                                    @else
                                                        <div class="input-field col s12">
                                                            <input type="text" id="name_{{$lang}}"
                                                                   name="langs[{{$lang}}][name]" value="" required/>
                                                            <label for="name_{{$lang}}"
                                                                   class="active">@lang('management.roles.form.name')
                                                                ({{$lang}})</label>
                                                        </div>
                                                    @endif
                                                @else
                                                    <div class="input-field col s12">
                                                        <input type="text" id="name_{{$lang}}"
                                                               name="langs[{{$lang}}][name]" value="" required/>
                                                        <label for="name_{{$lang}}"
                                                               class="active">@lang('management.roles.form.name')
                                                            ({{$lang}})</label>
                                                    </div>
                                                @endif
                                            @endforeach
                                            <div class="input-field col s12">
                                                <input type="text" id="alias" name="alias"
                                                       @if(isset($item->alias)) value="{{ $item->alias }}"
                                                       @endif required/>
                                                <label for="alias"
                                                       class="active">@lang('management.roles.form.alias')</label>
                                            </div>
                                            <div class="input-field col s12">
                                                <label>
                                                    <input type="checkbox" class="filled-in" name="restaurant_role"
                                                           @if(isset($item) && $item->restaurant_role) checked @endif/>
                                                    <span>@lang('management.roles.form.use')</span>
                                                </label>
                                            </div>
                                        </div>
                                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.account')
@section('seo')
    <title>@lang('management.roles.index.page_title')</title>
@endsection
@section('main')
    <div class="row">
        <div class="col s12">
            <h1 class="flow-text">@lang('management.roles.index.title')</h1>
            <div class="card">
                <div class="card-content">
                    <div class="row">
                        <div class="col s12 right-align">
                            <a href="{{ route('roles.create') }}" class="btn waves-effect waves-light">
                                @lang('management.roles.index.add')
                            </a>
                        </div>
                    </div>
                    @if($roles->count() == 0)
                        <div class="row">
                            <div class="col-12">
                                @lang('management.roles.index.empty')
                            </div>
                        </div>
                    @else
                        <table class="highlight responsive-table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Alias</th>
                                <th>@lang('management.roles.index.name')</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($roles as $key => $item)
                                <tr>
                                    <td>
                                        {{ $loop->iteration }}
                                    </td>
                                    <td>
                                        {{ $item->alias }}
                                    </td>
                                    <td>
                                        @foreach( $item->languages as $lang)
                                            @if($lang->language == app()->getLocale())
                                                {{ $lang->name }}
                                            @endif
                                        @endforeach
                                    </td>
                                    <td>
                                        <a href="{{ route('roles.edit', ['id' =>  $item->id ]) }}" title="@lang('management.roles.index.edit')">
                                            <i class="material-icons">edit</i>
                                        </a>
                                        <form method="post" action="{{ route('roles.destroy', ['id' => $item->id ]) }}">
                                            @method('DELETE')
                                            @csrf
                                            <button type="submit">
                                                <i class="material-icons red-text lighten-1-text">cancel</i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection