routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Middleware\Localization;

Route::get('/', function () {
    return redirect('/'. App::getLocale());
});
Route::get('lang/{locale}', 'HomeController@lang')->name('lang');

Route::get('/home', function (){
    return redirect('/'. App::getLocale());
})->name('home');

Route::group(['prefix' => Localization::getLocale()], function(){
    Auth::routes();
    Route::group(['prefix' => 'account'], function(){
        Route::middleware('can:accessAccount')->group(function(){
            /**
             * Admin part of routes
             */

            Route::resource('users', 'Admin\UsersController');
            Route::resource('restaurant-types', 'Admin\RestaurantTypes');
            Route::resource('cities', 'Admin\Cities');
            Route::resource('kitchens', 'Admin\KitchensController');
            Route::resource('restaurants', 'Admin\RestaurantsController');
            Route::resource('articles', 'Admin\ArticlesController');
            Route::resource('questions', 'Admin\QuestionController');
            Route::resource('roles', 'Admin\RolesController');
            Route::resource('event_types', 'Admin\EventTypeController');
            Route::resource('events', 'Admin\EventController');
            Route::resource('landings', 'Admin\LandingController');

            Route::resource('halls', 'Admin\HallsController')->only([
                'edit', 'update', 'destroy'
            ]);
            Route::get('/restaurants/{id}/halls/create', 'Admin\HallsController@create')->name('halls.create');
            Route::post('/restaurants/{id}/halls/store', 'Admin\HallsController@store')->name('halls.store');

            Route::resource('gallery', 'Admin\GalleryController')->only([
                'edit', 'update'
            ]);
            Route::resource('menu', 'Admin\MenuController')->only([
                'edit', 'update'
            ]);

            Route::resource('event_gallery', 'Admin\EventGalleryController')->only([
                'edit', 'update', 'destroy'
            ]);
            Route::get('/events/{id}/event_gallery/create', 'Admin\EventGalleryController@create')->name('event_gallery.create');
            Route::post('/events/{id}/event_gallery/store', 'Admin\EventGalleryController@store')->name('event_gallery.store');
            Route::post('/events/{id}/event_gallery/ajax_upload', 'Admin\AjaxUploadController@ajaxEventUpload')->name('event_gallery.ajax_upload');

            Route::post('/restaurants/{id}/halls/upload', 'Admin\AjaxUploadController@ajaxHallUpload')->name('halls.ajax_upload');
            Route::post('/restaurants/{id}/gallery/upload', 'Admin\AjaxUploadController@ajaxRestaurantUploadImage')->name('gallery.ajax_upload');
            Route::post('/restaurants/{id}/menu/upload', 'Admin\AjaxUploadController@ajaxMenuUploadImage')->name('menu.ajax_upload');
            Route::get('/remove-gallery-item/{id}', 'Admin\AjaxUploadController@removeGalleryItem')->name('remove_gallery_item'); //now must be get, because i don`t want write js of find solution for implementing delete method

            Route::get('/workload', 'Admin\WorkloadController@index')->name('workload-list');
            Route::get('/workload/{id}', 'Admin\WorkloadController@placeWorkload')->name('workload-place');
            Route::post('/workload/change-status', 'Admin\WorkloadController@changeStatus')->name('change-schedule');

            //Staff routes
            Route::get('/restaurants/{id}/staff/create', 'Admin\RestaurantsController@createStaff')->name('staff.create');
            Route::post('/restaurants/staff/store', 'Admin\RestaurantsController@storeStaff')->name('staff.store');
            Route::delete('/restaurant/staff/{id}/destroy', 'Admin\RestaurantsController@destroyStaff')->name('staff.destroy');

            Route::middleware('can:editSettings')->group(function(){
                Route::get('/resizes', 'Admin\ImageController@index')->name('resize-buttons');
                Route::post('/clean_resizes', 'Admin\ImageController@removeResizes')->name('clean-resizes');
                Route::post('/resize_one', 'Admin\ImageController@resizeOne')->name('resize-one');
                Route::post('/remove-wrong', 'Admin\ImageController@removeWrong')->name('remove-wrong');
            });
            /**
             * User part of cabinet routes
             */
            Route::get('/verified_notice', 'Account\SMSVerification@verifiedNotice')->name('phone_verification_notice');
            Route::post('/verified_notice', 'Account\SMSverification@checkVerification')->name('check_verification');
            Route::get('/send_verification_code', 'Account\SMSVerification@sendVerificationCode')->name('send_verification');
            Route::get('/dashboard', 'Account\Dashboard@index')->name('account')->middleware('phone_verified');

            Route::resource('my-orders', 'Account\OrderController');
            Route::resource('pouch', 'Account\PouchController');
            Route::resource('transactions', 'Account\TransactionsController');
            Route::resource('account-settings', 'Account\UserController');
            /**
             * Routes for restaurant management
             */
            Route::get('/restaurant/{restaurant_id}/orders', 'RestaurantManagement\OrdersController@index')->name('restaurant.orders');
            Route::get('/restaurant/{restaurant_id}/orders/{order_id}', 'RestaurantManagement\OrdersController@show')->name('restaurant.orders.show');
            Route::get('/restaurant/{restaurant_id}/orders/{order_id}/edit', 'RestaurantManagement\OrdersController@edit')->name('restaurant.orders.edit');
            Route::put('/restaurant/orders/{order_id}/update', 'RestaurantManagement\OrdersController@update')->name('restaurant.orders.update');
            Route::put('/restaurant/orders/{order_id}/accept', 'RestaurantManagement\OrdersController@accept')->name('restaurant.orders.accept');
            Route::put('/restaurant/orders/{order_id}/reject', 'RestaurantManagement\OrdersController@reject')->name('restaurant.orders.reject');
            Route::put('/restaurant/orders/{order_id}/user_reject', 'RestaurantManagement\OrdersController@user_cancel')->name('restaurant.orders.user_reject');
            //pay
            //check for payed and cancel if not
            //user reject with back money
            //success
            //confirm success


        });
    });

    Route::get('/create-sitemap', 'SitemapController@index')->name('sitemap');
    //Route::get('/test', 'LiqpayController@create');
    Route::get('/', 'HomeController@index')->name('start');
    Route::post('/show_city', 'HomeController@cities_form')->name('select-city');
    Route::get('/FAQ', 'ArticlesController@view_faq')->name('faq');
    Route::get('/{uri}', 'HomeController@city')->name('city-page');
    Route::get('/articles/{article_uri}', 'ArticlesController@index')->name('view-article');
    Route::get('/{city_ur}/filter', 'HomeController@filter')->name('filter');
    Route::get('/{city_uri}/{restaurant_uri}', 'RestaurantController@index')->name('restaurant-page');
    Route::post('/{city_uri}/{restaurant_uri}/order', 'OrdersController@create')->name('order.create');
    Route::get('/{city_uri}/{restaurant_uri}/order', 'OrdersController@continue')->name('order.continue');
    Route::post('/{restaurant}/order/store', 'OrdersController@store')->name('order.store');

});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $table = 'articles';

    protected $fillable = [
        'uri',
        'isTopMenu',
        'isFooter_1',
        'isFooter_2',
        'isBlog',
        'status',
        'sorting'
    ];

    public function languages()
    {
        return $this->morphMany(Language::class, 'owner');
    }
}

app/Http/Controllers/Admin/ArticlesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Article;
use App\Language;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;

class ArticlesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('can:edit-articles');
    }

    /**
     * Show list of articles
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(){
        $data['articles'] = Article::where('type', '=', 'article')->with('languages')->get();
        return view('admin.articles.index', $data);
    }

    /**
     * Show form for create article
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(){
        return view('admin.articles.form');
    }

    /**
     * Save article
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request){

        $validatedData = $request->validate([
            'uri'                 => 'required|unique:cities|regex:/^[a-z_0-9\.-]+$/i',
            'langs.*.title'        => 'required',
            'langs.*.seo_title'   => 'required',
        ]);
        $article = new Article();

        $article->uri        = $request->uri;
        $article->sorting    = $request->sorting ?: 0;
        $article->type       = 'article';
        $article->status     = $request->status == "on";
        $article->isTopMenu  = $request->isTopMenu == "on";
        $article->isFooter_1 = $request->isFooter_1 == "on";
        $article->isFooter_2 = $request->isFooter_2 == "on";
        $article->isBlog     = $request->isBlog == "on";
        $article->save();


        $langs = [];
        foreach($request->langs as $key => $lang) {
            $langs[$key] = new Language();
            $langs[$key]->fill(array(
                'language'         => $key,
                'title'            => $lang['title'],
                'seo_title'        => $lang['seo_title'],
                'seo_description'  => $lang['seo_description'],
                'description'      => $lang['content'],
            ));
            $article->languages()->save($langs[$key]);
        }
        return redirect()->route('articles.index');
    }

    /**
     * Show form for edit article
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id){
        $data['article'] = Article::where([['id', '=', $id], ['type', '=', 'article']])->with('languages')->first();
        foreach($data['article']->languages as $lang){
            $data['article_lang'][$lang->language]['title'] = $lang->title;
            $data['article_lang'][$lang->language]['seo_title'] = $lang->seo_title;
            $data['article_lang'][$lang->language]['seo_description'] = $lang->seo_description;
            $data['article_lang'][$lang->language]['content'] = $lang->description;
        }
        return view('admin.articles.form', $data);
    }


    /**
     * Update article
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id){
        $validatedData = $request->validate([
            'uri'                 => [
                'required',
                'regex:/^[a-z_0-9\.-]+$/i',
                Rule::unique('articles')->ignore($id),
            ],
            'langs.*.title'       => 'required',
            'langs.*.seo_title'   => 'required',
        ]);
        $article = Article::where([['id', '=', $id], ['type', '=', 'article']])->with('languages')->first();

        $article->uri        = $request->uri;
        $article->sorting    = $request->sorting ?: 0;
        $article->type       = 'article';
        $article->status     = $request->status == "on";
        $article->isTopMenu  = $request->isTopMenu == "on";
        $article->isFooter_1 = $request->isFooter_1 == "on";
        $article->isFooter_2 = $request->isFooter_2 == "on";
        $article->isBlog     = $request->isBlog == "on";
        $article->save();

        foreach($request->langs as $key => $lang) {
            foreach($article->languages as $article_lang){
                if($article_lang->language == $key){
                    $article_lang->title           = $lang['title'];
                    $article_lang->seo_title       = $lang['seo_title'];
                    $article_lang->seo_description = $lang['seo_description'];
                    $article_lang->description     = $lang['content'];
                }
                $article_lang->save();
            }
        }

        return redirect()->route('articles.index');
    }


    /**
     * Delete article
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Exception
     */
    public function destroy($id){
        $item = Article::findOrFail($id);
        $item->languages()->delete();
        $item->delete();

        return redirect()->route('articles.index');
    }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use Illuminate\Http\Request;

class ArticlesController extends Controller
{

    public function index($article_uri){
        $data['article'] = Article::where([['uri', '=', $article_uri], ['type', '=', 'article']])->with('languages')->first();
        return view('public.article', $data);
    }

    public function view_faq(){
        $data['questions'] = Article::where([['type', '=', 'question'], ['status', '=', true]])->with('languages')->get();
        return view('public.faq', $data);
    }

}

resources/views/admin/articles/form.blade.php
@extends ('layouts.account')
@section('seo')
    <title>@lang('management.articles.form.page_title')</title>
@endsection
@section('scripts')
    @include('admin.components.tinymce_script')
@endsection

@section('main')
    <div class="row">
        <div class="col s12">
            <h1 class="flow-text">
                @if(isset($article_lang))
                    {{ $article_lang[app()->getLocale()]['title'] }}
                @else
                    @lang('management.articles.form.new')
                @endif
            </h1>
            <div class="card">
                <div class="card-content">
                    <div class="row">
                        @if(isset($article))
                            <form class="col s12" method="post" action="{{ route('articles.update', ['id' => $article->id]) }}">
                                @method('PATCH')
                        @else
                            <form class="col s12" method="post" action="{{ route('articles.store') }}">
                        @endif
                        @csrf
                        <div class="row">
                            <div class="col s12 right-align">
                                <button class="btn waves-effect waves-light" type="submit">
                                    @lang('management.articles.form.save')
                                    <i class="material-icons right">save</i>
                                </button>
                            </div>
                        </div>
                        @if ($errors->count() > 0)
                            <div class="row">
                                <ul class="col s-12">
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif

                        <div class="row">
                            <div class="col s12">
                                <ul class="tabs">
                                    <li class="tab col s3"><a class="active" href="#settings">@lang('management.articles.form.settings')</a></li>
                                    @foreach(config('app.locales') as $key => $lang)
                                        <li class="tab col s3"><a href="#{{ $lang }}">{{ $lang }}</a></li>
                                    @endforeach
                                </ul>
                            </div>

                            <div id="settings" class="col s12">
                                <div class="row">
                                    <div class="input-field col s12">
                                        <input @if(isset($article)) value="{{$article->uri}}" @endif id="uri" name="uri" type="text" class="validate  @error('uri') invalid @enderror" required>
                                        <label class="active" for="uri">URI</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s6">
                                        <label>
                                            <input type="checkbox" class="filled-in" name="status" @if(isset($article) && $article->status) checked @endif/>
                                            <span>@lang('management.articles.form.publicate')</span>
                                        </label>
                                    </div>
                                    <div class="input-field col s6">
                                        <input @if(isset($article)) value="{{$article->sorting}}" @else value="0" @endif id="sorting" name="sorting" type="number" class="validate  @error('sorting') invalid @enderror" required>
                                        <label class="active" for="sorting">@lang('management.articles.form.order')</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <h2 class="flow-text">@lang('management.articles.form.position')</h2>
                                    <div class="input-field col s12">
                                        <label>
                                            <input type="checkbox" class="filled-in" name="isTopMenu" @if(isset($article) && $article->isTopMenu) checked @endif/>
                                            <span>@lang('management.articles.form.top_menu')</span>
                                        </label>
                                    </div>
                                    <div class="input-field col s12">
                                        <label>
                                            <input type="checkbox" class="filled-in" name="isFooter_1" @if(isset($article) && $article->isFooter_1) checked @endif/>
                                            <span>@lang('management.articles.form.bottom_1')</span>
                                        </label>
                                    </div>
                                    <div class="input-field col s12">
                                        <label>
                                            <input type="checkbox" class="filled-in" name="isFooter_2" @if(isset($article) && $article->isFooter_2) checked @endif/>
                                            <span>@lang('management.articles.form.bottom_2')</span>
                                        </label>
                                    </div>
{{--                                    <div class="input-field col s12">--}}
{{--                                        <label>--}}
{{--                                            <input type="checkbox" class="filled-in" name="isBlog" @if(isset($article) && $article->isBlog) checked @endif/>--}}
{{--                                            <span>Блог</span>--}}
{{--                                        </label>--}}
{{--                                    </div>--}}
                                </div>
                            </div>

                            @foreach(config('app.locales') as $lang)
                                <div id="{{$lang}}" class="col s12">
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <input
                                                @if(isset($article_lang)) value="{{ $article_lang[$lang]['title']}}" @endif
                                            id="description_{{$lang}}"
                                                name="langs[{{ $lang }}][title]"
                                                type="text" class="validate  @error('info') invalid @enderror"
                                                required>
                                            <label class="active" for="description_{{$lang}}">@lang('management.articles.form.heading')</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <input
                                                @if(isset($article_lang)) value="{{$article_lang[$lang]['seo_title']}}" @endif
                                            id="seo_title_{{$lang}}"
                                                name="langs[{{$lang}}][seo_title]"
                                                type="text"
                                                class="validate  @error('surname') invalid @enderror" required>
                                            <label class="active" for="seo_title_{{$lang}}">SEO title</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="input-field col s12">
                                            <textarea
                                                id="seo_description_{{$lang}}"
                                                name="langs[{{$lang}}][seo_description]"
                                                type="text"
                                                class="materialize-textarea validate  @error('surname') invalid @enderror">@if(isset($article_lang)){{$article_lang[$lang]['seo_description']}}@endif</textarea>
                                            <label class="active" for="seo_description_{{$lang}}">SEO description</label>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col s12">
                                            <label>
                                                @lang('management.articles.form.text')
                                            </label>
                                            <textarea
                                                id="content_{{$lang}}"
                                                name="langs[{{$lang}}][content]"
                                                hidden>@if(isset($article_lang)){{$article_lang[$lang]['content']}}@endif</textarea>
                                        </div>
                                    </div>
                                </div>
                                @endforeach
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/articles/index.blade.php
@extends ('layouts.account')
@section('seo')
    <title>@lang('management.articles.index.page_title')</title>
@endsection
@section('main')
    <div class="row">
        <div class="col s12">
            <h1 class="flow-text">@lang('management.articles.index.page_title')</h1>
            <div class="card">
                <div class="card-content">
                    <div class="row">
                        <div class="col s12 right-align">
                            <a href="{{ route('articles.create') }}" class="btn waves-effect waves-light">
                                @lang('management.articles.index.add')
                            </a>
                        </div>
                    </div>
                    @if($articles->count() == 0)
                        <div class="row">
                            <div class="col-12">
                                @lang('management.articles.index.empty')
                            </div>
                        </div>
                    @else
                        <table class="highlight responsive-table">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>URI</th>
                                <th>@lang('management.articles.index.name')</th>
                                <th>@lang('management.articles.index.status')</th>
                                <th>@lang('management.articles.index.order')</th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($articles as $article)
                                <tr>
                                    <td>
                                        {{ $loop->iteration }}
                                    </td>
                                    <td>
                                        {{ $article->uri }}
                                    </td>
                                    <td>
                                        @foreach( $article->languages as $lang)
                                            @if($lang->language == app()->getLocale())
                                                {{ $lang->title }}
                                            @endif
                                        @endforeach
                                    </td>
                                    <td>
                                        @if($article->status)
                                            @lang('management.articles.index.publicated')
                                        @else
                                            @lang('management.articles.index.unpublicated')
                                        @endif
                                    </td>
                                    <td>
                                        {{ $article->sorting }}
                                    </td>
                                    <td>
                                        <a href="{{route('articles.edit', ['id' => $article->id])}}" title="@lang('management.articles.index.edit')">
                                            <i class="material-icons">edit</i>
                                        </a>
                                        <form method="post" action="{{route('articles.destroy', ['id' => $article->id])}}">
                                            @method('DELETE')
                                            @csrf
                                            <button type="submit">
                                                <i class="material-icons red-text lighten-1-text">cancel</i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection